### ISSUE TITLE
[NOT AN ISSUE] Dockerize SQLite3 to MySQL

### ISSUE THREAD

**Issue by SmartPhoneLover** [benrowe/mysql-to-sqlite3#3]
Hello, I would like to know if you can, as you made with the [MySQL to SQLite3](https://github.com/techouse/mysql-to-sqlite3) project, dockerize the other one, called: '[SQLite3 to MySQL](https://github.com/techouse/sqlite3-to-mysql)'.

Thank you.

**Comment by benrowe** [comment]
Sorry but i have no current plans to implement an image for this.
